version: "3.8"
services:
  db:
    image:postgres:13.4-alpine
    container_name:"database"
    ports:
      - "5432:5432" 
    environment:
      - POSTGRES_DB=employee_mgmnt
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    networks:
      - emp-mgmnt-system
    volumes:
      - database_postgres:/var/lib/postgresql/data
  api:
    build: .
    container_name: "rest-api"
    environment:
      DB_HOST:"db"
      DB_USER:"postgres"
      DB_PASSWORD:"postgres"
      DB_DATABASE:"employee_mgmnt"
    ports:
      - "9000:9000"
    depends_on:
      - db
    networks:
      - emp-mgmnt-system
volumes:
  - database_postgres:
networks:
  emp-mgmnt-system:
    driver:bridge